### ISSUE TITLE
Ajouter un lien vers la page de status

### ISSUE THREAD

**Issue by sandcha** [openfisca/fr.openfisca.org#14]
Ajouter un lien vers cette [page de status](https://status.openfisca.fr) qui est indiquée dans le [README.md de la documentation](https://github.com/openfisca/openfisca-doc/blob/0e2e6af97f06588efe6e4a38c2ddd483ab5962c1/README.md#web-api) mais peu découvrable ?

**Comment by renardpal** [comment]
superseaded by #21
