### ISSUE TITLE
Publier le site minimal viable

### ISSUE THREAD

**Issue by sandcha** [openfisca/fr.openfisca.org#21]
Publier la nouvelle version du site produite suite aux tests utilisateurs (voir [maquette figma](https://www.figma.com/file/qZ2QJxYB2dtmzeoKH2nFvF/Refonte_FR?node-id=216%3A4357&redirected=1)).

Reste à faire : 

- [x] Composants Head & Hero : burger menu au resize
- [x] Toutes pages : régler le responsive
- [x] Toutes pages : relecture pour erreurs typo qui traineraient
- [x] Remplir tous les alt img et liens
- [x] Composant CardProject : arriver à avoir une hauteur fixe
- [x] Page Communauté : Ajouter formulaire de contact
- [x] Améliorer le positionnements des icônes SVG (dans les boutons > centrer avec le texte)
- [x] Vérifier la configuration Piwik
- [x] Publier (voir publication automatique du bot dans configuration .circleci)

**Comment by renardpal** [comment]
I added empty alt"" on all the decorative images and icons. I have a doubt about the social links in the footer: the img alt describes the icon but I'm not sure it substitutes to the fact the link is empty.
I added <title> in the header component but it doesn't show on the local version so maybe it wasn't the proper way to do it...

**Comment by Morendil** [comment]
Fermée via #24
