### ISSUE TITLE
Améliorer la qualité du rendu graphique

### ISSUE THREAD

**Issue by renardpal** [openfisca/fr.openfisca.org#33]
Liste des éléments restants à régler / améliorer : 
- [x] INDEX positionnement des icônes / titres des cibles
<img width="595" alt="Capture d’écran 2019-04-24 à 17 20 39" src="https://user-images.githubusercontent.com/44638568/56671734-6f10da80-66b5-11e9-9f25-de1690903a2c.png">

- [ ] RESSOURCES même positionnement des icônes / titre des cards
- [x] RESSOURCES se rapprocher de la maquette pour avoir 2 btns associés et une condition > si explorer n'a pas d'url, pas de bouton affiché
<img width="767" alt="Capture d’écran 2019-04-24 à 17 19 48" src="https://user-images.githubusercontent.com/44638568/56671763-7801ac00-66b5-11e9-9c88-18fd3991658a.png">

- [x] ALL PAGES régler les bugs de responsive sur Chrome...

- [ ] NAV créer un burger menu au lieu du flex/colum au resize
- [x] NAV ajouter un lien "en" vers le .org pour faire le pont entre les deux sites dans l'attente du site EN
- [x] RESSOURCES remplacer assets pays par assets drapeau (sinon on va pas s'en sortir)
- [ ] HEADER ajouter un favicon !

**Comment by sandcha** [comment]
@renardpal On y est presque 🙌 
Aurais-tu le favicon à placer sur le site ?

**Comment by MattiSG** [comment]
En l'absence d'équipe dédiée à ce sujet, je ferme cette issue qui sera le cas échéant reconsidérée par une future équipe.
